version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: proyecto-backend
    environment:
      PORT: 5000
      CORS_ORIGIN: http://35.239.188.208
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: proyecto-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend

  sonarqube:
    image: sonarqube:lts-community
    container_name: proyecto-sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_WEB_CONTEXT: /sonarqube
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: proyecto-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.2.0
    container_name: proyecto-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_SERVER_ROOT_URL: http://35.239.188.208/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: proyecto-cadvisor
    privileged: true
    ports:
      - "3002:8080"
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  grafana_data:
  sonar_data:
  sonar_extensions:
  sonar_logs:
