sonar.projectKey=proyecto-node
sonar.projectName=proyecto-node
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src
sonar.tests=backend/__tests__,frontend/src
sonar.test.inclusions=backend/__tests__/**/*.js,frontend/src/**/*.test.js
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/public/**,**/*.config.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
